### PR TITLE
Resolves issue #66

### PR DESCRIPTION
**Pull request by peter279k**
Resolves issue #66

### CODE REVIEW

**Comment by peter279k** [comment]
The Travis CI build is failed due to the `sonar-scanner command not found` problem.

@s3b4stian, do you have any idea about this?

**Comment by s3b4stian** [comment]
Ok @peter279k now all works! I also have another solution! check it:

```php
class Password
{
    /**
     * @var array An associative array containing options
     *
     * http://php.net/manual/en/function.password-hash.php
     */
    // The key is the same value for PASSWORD_* constant
    protected $options = [
        //PASSWORD_DEFAULT or PASSWORD_BCRYPT value is 1
        1 => ['cost' => 11],
        //PASSWORD_ARGON2I value is 2
        2 => [
            'memory_cost' => 1024,
            'time_cost' => 2,
            'threads' => 2
        ]
    ];

    //NOT NEEDED
    /**
     * @var array An associate array containing algorithm constants
     */
    //protected $algoLists = [
    //    PASSWORD_BCRYPT,
    //    PASSWORD_DEFAULT
    //];

    /**
     * @var int Password default algorithm
     */
    protected $algo = 1;

    /**
     * Class constructor.
     * <p>For password algorithm constants see <a href="http://php.net/manual/en/password.constants.php">Password Constants</a>.</p>
     * <pre><code class="php">//Options passed to class constructor as ['key' => 'value'] array.
     * $password = new Password(PASSWORD_DEFAULT, [
     *     'cost' => 11
     * ]);
     * </code></pre>
     *
     * @param int   $algo
     * @param array $options
     *
     * @throws \InvalidArgumentException
     */
    public function __construct(int $algo = PASSWORD_DEFAULT, array $options = [])
    {
        //NOT NEEDED
        //necessary for avoid errors if Argon2 library not enabled
        //PASSWORD_ARGON2ID const only present since 7.3 PHP version
        //if (\defined('PASSWORD_ARGON2I')) {
        //    $this->algoLists[] = PASSWORD_ARGON2I;
        //}

        if (\defined('PASSWORD_ARGON2ID')) {
            // Options for ARGON2I and ARGON2ID are the same but
            // PASSWORD_ARGON2ID value is 3 (verified with php 7.3 installation)
            $this->options[3] = $this->options[2];
        }

        //if algo not present in options then trow exception
        if (empty($this->options[$algo])) {
            throw new \InvalidArgumentException('The password algorithm name is invalid');
        }

        $this->algo = $algo;
        $this->options[$algo] = \array_replace_recursive($this->options[$algo], $options);
    }
   
    //OTHER METHODS
}
```

Give me your feedback! Thanks

**Comment by peter279k** [comment]
Hi @s3b4stian, thank you for your reply.

Most of enhancements look good to me.

But I have some suggestions are as follows:

- We should use the `PASSWORD_*` const values rather than using the integer value directly because of the code readability.
- I think you can use the code review [feature](https://github.com/linna/framework/pull/67/files) which is available on GitHub. And it can be more helpful than writing the comment directly in discussion thread :).

**Comment by s3b4stian** [comment]
Hello @peter279k 

Now I merge pull request!

* Use of integer key was a trick for avoid problems in case of Argon2 library missing.
* I already used code review feature, this time I was in a hurry.

Bye!

**Pull request merged**
